name       : gopass
version    : 1.14.11
release    : 25
source     :
    - https://github.com/gopasspw/gopass/releases/download/v1.14.11/gopass-1.14.11.tar.gz : cd0fd946e0ccc8781ed2087f3d4a4d18facd4cb0b2b6d20d3403c766379afef9
    - https://github.com/gopasspw/git-credential-gopass/releases/download/v1.14.11/git-credential-gopass-1.14.11.tar.gz : 63ea53eab7f45258bb04b855dde7a4de53cd40475873d9f27d89e11094330668
    - https://github.com/gopasspw/gopass-hibp/releases/download/v1.14.11/gopass-hibp-1.14.11.tar.gz : 72e66c83b4360f44527f3375f8fa376228345085a3c3c0cc334f95d200c66c76
    - https://github.com/gopasspw/gopass-jsonapi/releases/download/v1.14.11/gopass-jsonapi-1.14.11.tar.gz : afb6053bd6bd628dcdef5deeb364fcabfe7830d4519b5ea71a3763cf7588760f
    - https://github.com/gopasspw/gopass-summon-provider/releases/download/v1.14.11/gopass-summon-provider-1.14.11.tar.gz : 5c2b73d9a6b55299099eca3cbda73d6cb1b37604d86f0b3436cadeac5ae19c77
license    : MIT
component  : security
networking : yes
summary    : The slightly more awesome standard unix password manager for teams
description: |
    gopass is a rewrite of the pass password manager in Go with the aim of making it cross-platform and adding additional features.
builddeps  :
    - golang
rundeps    :
    - git
    - gnupg
    - xdotool
    - xsel
setup      : |
    for i in git-credential-gopass gopass-{hibp,jsonapi,summon-provider}; do
        mkdir -p integrations/$i
        tar -x -C integrations/$i -f $sources/$i-*.tar.gz
    done

    # Remove missing install-completion target
    # See: https://github.com/gopasspw/git-credential-gopass/issues/3
    sed -i 's/install-completion//' integrations/*/Makefile
build      : |
    %make
    for i in integrations/*; do
        %make -C $i
    done
install    : |
    %make_install PREFIX=/usr
    for i in integrations/*; do
        %make_install -C $i PREFIX=/usr
    done

    # Set correct permission bits for the shell completion files
    chmod 644 $installdir/usr/share/zsh/site-functions/_gopass
    chmod 644 $installdir/usr/share/bash-completion/completions/gopass
    chmod 644 $installdir/usr/share/fish/vendor_completions.d/gopass.fish
