name       : gopass
version    : 1.8.3
release    : 4
source     :
    - https://github.com/gopasspw/gopass/releases/download/v1.8.3/gopass-1.8.3.tar.gz : 18281e07de961b26b9cce7c907e811d567b0e599649f0dbe703ab108984275a8
license    : MIT
component  : security
summary    : The slightly more awesome standard unix password manager for teams
description: |
    gopass is a rewrite of the pass password manager in Go with the aim of making it cross-platform and adding additional features.
builddeps  :
    - golang
rundeps    :
    - git
    - gnupg
    - xdotool
    - xsel
build      : |
    mv vendor src
    mkdir -p src/github.com/gopasspw
    ln -s $workdir src/github.com/gopasspw/gopass
    %make GOPATH=$workdir
install    : |
    %make_install GOPATH=$workdir PREFIX=/usr

    # Set correct permission bits for the shell completion files
    chmod 644 $installdir/usr/share/zsh/site-functions/_gopass
    chmod 644 $installdir/usr/share/bash-completion/completions/gopass
    chmod 644 $installdir/usr/share/fish/vendor_completions.d/gopass.fish
