name       : gopass
version    : 1.15.0
release    : 26
source     :
    - https://github.com/gopasspw/gopass/releases/download/v1.15.0/gopass-1.15.0.tar.gz : afdc424cfe2b0c29f0cde616f3eb233e6dbe3787741582449de0c90314ec1e29
    - https://github.com/gopasspw/git-credential-gopass/releases/download/v1.15.0/git-credential-gopass-1.15.0.tar.gz : 3a733a71b4ec6d9609162c66bc1fa5c77e16e825c5d33748565658ecb0353449
    - https://github.com/gopasspw/gopass-hibp/releases/download/v1.15.0/gopass-hibp-1.15.0.tar.gz : 7a145ef84db61eb7beb4f3377d4aa240006510199b1f36ab248720858f2ea647
    - https://github.com/gopasspw/gopass-jsonapi/releases/download/v1.15.0/gopass-jsonapi-1.15.0.tar.gz : c4b8e1cdfe64010798e93643b6590621d004794c558edd976da8f9b3861ea538
    - https://github.com/gopasspw/gopass-summon-provider/releases/download/v1.15.0/gopass-summon-provider-1.15.0.tar.gz : 6897fbf6074fcd744cb5be5b482ca338384f4e5d440ce493dd9039e877ca4e48
license    : MIT
component  : security
networking : yes
summary    : The slightly more awesome standard unix password manager for teams
description: |
    gopass is a rewrite of the pass password manager in Go with the aim of making it cross-platform and adding additional features.
builddeps  :
    - golang
rundeps    :
    - git
    - gnupg
    - xdotool
    - xsel
setup      : |
    for i in git-credential-gopass gopass-{hibp,jsonapi,summon-provider}; do
        mkdir -p integrations/$i
        tar -x -C integrations/$i -f $sources/$i-*.tar.gz
    done

    # Remove missing install-completion target
    # See: https://github.com/gopasspw/git-credential-gopass/issues/3
    sed -i 's/install-completion//' integrations/*/Makefile
build      : |
    %make
    for i in integrations/*; do
        %make -C $i
    done
install    : |
    %make_install PREFIX=/usr
    for i in integrations/*; do
        %make_install -C $i PREFIX=/usr
    done

    # Set correct permission bits for the shell completion files
    chmod 644 $installdir/usr/share/zsh/site-functions/_gopass
    chmod 644 $installdir/usr/share/bash-completion/completions/gopass
    chmod 644 $installdir/usr/share/fish/vendor_completions.d/gopass.fish
