name       : gopass
version    : 1.14.6
release    : 23
source     :
    - https://github.com/gopasspw/gopass/releases/download/v1.14.6/gopass-1.14.6.tar.gz : ac1707a6043336f14b08c1e0add2d970ff8b07885fdf105b8497001f47046651
    - https://github.com/gopasspw/git-credential-gopass/releases/download/v1.14.6/git-credential-gopass-1.14.6.tar.gz : 5c3e1c72cd7ebcffd299f5db638faa5b581bbbd88c20071c68d992469bdc87a2
    - https://github.com/gopasspw/gopass-hibp/releases/download/v1.14.6/gopass-hibp-1.14.6.tar.gz : 3f0d3fec341bda6b2ab314bc7ca7923a3ca1752f19e286206a7ce8c2a1217e50
    - https://github.com/gopasspw/gopass-jsonapi/releases/download/v1.14.6/gopass-jsonapi-1.14.6.tar.gz : 3ce434ee44c2cd17ac241bfc4a62e95d98d0e78e068f78a7d71106a4d555c6b3
    - https://github.com/gopasspw/gopass-summon-provider/releases/download/v1.14.6/gopass-summon-provider-1.14.6.tar.gz : 3dfea9ae8f8779c7c8c350df32316b015b94fa453fe8b7a242359cb800b577a6
license    : MIT
component  : security
networking : yes
summary    : The slightly more awesome standard unix password manager for teams
description: |
    gopass is a rewrite of the pass password manager in Go with the aim of making it cross-platform and adding additional features.
builddeps  :
    - golang
rundeps    :
    - git
    - gnupg
    - xdotool
    - xsel
setup      : |
    for i in git-credential-gopass gopass-{hibp,jsonapi,summon-provider}; do
        mkdir -p integrations/$i
        tar -x -C integrations/$i -f $sources/$i-*.tar.gz
    done

    # Remove missing install-completion target
    # See: https://github.com/gopasspw/git-credential-gopass/issues/3
    sed -i 's/install-completion//' integrations/*/Makefile
build      : |
    %make
    for i in integrations/*; do
        %make -C $i
    done
install    : |
    %make_install PREFIX=/usr
    for i in integrations/*; do
        %make_install -C $i PREFIX=/usr
    done

    # Set correct permission bits for the shell completion files
    chmod 644 $installdir/usr/share/zsh/site-functions/_gopass
    chmod 644 $installdir/usr/share/bash-completion/completions/gopass
    chmod 644 $installdir/usr/share/fish/vendor_completions.d/gopass.fish
