name       : gopass
version    : 1.8.2
release    : 3
source     :
    - https://github.com/gopasspw/gopass/releases/download/v1.8.2/gopass-1.8.2.tar.gz : ca6d24db014a760f71fbf0edaad0c97c283a670b260275a78eda3a7456fbea93
license    : MIT
component  : security
summary    : The slightly more awesome standard unix password manager for teams
description: |
    gopass is a rewrite of the pass password manager in Go with the aim of making it cross-platform and adding additional features.
builddeps  :
    - golang
rundeps    :
    - git
    - gnupg
    - xdotool
    - xsel
build      : |
    mv vendor src
    mkdir -p src/github.com/gopasspw
    ln -s $workdir src/github.com/gopasspw/gopass
    GOPATH=$workdir %make
install    : |
    GOPATH=$workdir PREFIX=/usr %make_install

    # Set correct permission bits for the shell completion files
    chmod 644 $installdir/usr/share/zsh/site-functions/_gopass
    chmod 644 $installdir/usr/share/bash-completion/completions/gopass
    chmod 644 $installdir/usr/share/fish/vendor_completions.d/gopass.fish
