name       : gopass
version    : 1.15.7
release    : 30
source     :
    - https://github.com/gopasspw/gopass/archive/refs/tags/v1.15.7.tar.gz#gopass.tar.gz : 35d1af333de479e429da31427b70b2043e20ef9a7ab0f8b816867ffc6f44927b
    - https://github.com/gopasspw/git-credential-gopass/archive/refs/tags/v1.15.7.tar.gz#git-credential-gopass.tar.gz : ac561ca0b726adeed6f69a4c2bedf4c9c1b8e9ba389eaa3335c6d7277586bcb1
    - https://github.com/gopasspw/gopass-hibp/archive/refs/tags/v1.15.7.tar.gz#gopass-hibp.tar.gz : 450b93d310f25e8e248d2f5218cba94a0b8e3966671e16c37c2c402ae7589580
    - https://github.com/gopasspw/gopass-jsonapi/archive/refs/tags/v1.15.7.tar.gz#gopass-jsonapi.tar.gz : 08ec445cc6929c7887caa3c631ab1aa73def89ca35f16160e5ff2ce535a0370b
    - https://github.com/gopasspw/gopass-summon-provider/archive/refs/tags/v1.15.7.tar.gz#gopass-summon-provider.tar.gz : 3f1cb63306ef3e3c5fefbd2a1eead10d790a39ab0b42d33560d922427fd1dcf3
license    : MIT
component  : security
networking : yes
summary    : The slightly more awesome standard unix password manager for teams
description: |
    gopass is a rewrite of the pass password manager in Go with the aim of making it cross-platform and adding additional features.
builddeps  :
    - golang
rundeps    :
    - git
    - gnupg
    - xdotool
    - xsel
setup      : |
    mkdir -p integrations
    for i in git-credential-gopass gopass-{hibp,jsonapi,summon-provider}; do
        tar -x -C integrations -f $sources/$i.tar.gz
    done
build      : |
    %make
    for i in integrations/*; do
        %make -C $i
    done
install    : |
    %make_install PREFIX=/usr
    for i in integrations/*; do
        %make_install -C $i PREFIX=/usr
    done

    # Set correct permission bits for the shell completion files
    chmod 644 $installdir/usr/share/zsh/site-functions/_gopass
    chmod 644 $installdir/usr/share/bash-completion/completions/gopass
    chmod 644 $installdir/usr/share/fish/vendor_completions.d/gopass.fish
