name       : gopass
version    : 1.15.1
release    : 27
source     :
    - https://github.com/gopasspw/gopass/releases/download/v1.15.1/gopass-1.15.1.tar.gz : 0418700a9540997d658166c9a6b97361e7d6e6e0d83c6a347bc69b1b4533bfcf
    - https://github.com/gopasspw/git-credential-gopass/releases/download/v1.15.1/git-credential-gopass-1.15.1.tar.gz : 38d1e058f3baf16af265fcf278498d42f9fe51ace5c16462ac3f4087c0209822
    - https://github.com/gopasspw/gopass-hibp/releases/download/v1.15.0/gopass-hibp-1.15.0.tar.gz : 7a145ef84db61eb7beb4f3377d4aa240006510199b1f36ab248720858f2ea647
    - https://github.com/gopasspw/gopass-jsonapi/releases/download/v1.15.1/gopass-jsonapi-1.15.1.tar.gz : b3463f74c563f8220ef9714c660b52eeff88de3ea9e461f46928241b28e565b4
    - https://github.com/gopasspw/gopass-summon-provider/releases/download/v1.15.1/gopass-summon-provider-1.15.1.tar.gz : 98c0f0580235dd9e152454302033421ae5c784b020dc34faf22b21db835c956d
license    : MIT
component  : security
networking : yes
summary    : The slightly more awesome standard unix password manager for teams
description: |
    gopass is a rewrite of the pass password manager in Go with the aim of making it cross-platform and adding additional features.
builddeps  :
    - golang
rundeps    :
    - git
    - gnupg
    - xdotool
    - xsel
setup      : |
    for i in git-credential-gopass gopass-{hibp,jsonapi,summon-provider}; do
        mkdir -p integrations/$i
        tar -x -C integrations/$i -f $sources/$i-*.tar.gz
    done

    # Remove missing install-completion target
    # See: https://github.com/gopasspw/git-credential-gopass/issues/3
    sed -i 's/install-completion//' integrations/*/Makefile
build      : |
    %make
    for i in integrations/*; do
        %make -C $i
    done
install    : |
    %make_install PREFIX=/usr
    for i in integrations/*; do
        %make_install -C $i PREFIX=/usr
    done

    # Set correct permission bits for the shell completion files
    chmod 644 $installdir/usr/share/zsh/site-functions/_gopass
    chmod 644 $installdir/usr/share/bash-completion/completions/gopass
    chmod 644 $installdir/usr/share/fish/vendor_completions.d/gopass.fish
